variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build-dependencies
  - build
  - test
  - deploy
  

build-sharpneat:
  stage: build-dependencies
  script:
    - echo "building SharpNeat"

build-emu:
  stage: build-dependencies
  script:
    - echo "building Bizhawk"
    
build-app:
  stage: build
  script:
    - echo "building SMW-ML"
    
test-app:
  stage: test
  script:
    - echo "running tests"
    
deploy-app:
  stage: deploy
  script:
    - echo "deploying artifacts"