variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build-dependencies
  - build
  - test
  
build-sharpneat:
  stage: build-dependencies
  script:
    - cd .\Submodules\SharpNEAT\src\
    - dotnet build --configuration Release
    - cd .\..\..\..\
    
build-emu:
  stage: build-dependencies
  script:
    - cd .\Submodules\BizHawk\Dist\
    - .\QuickTestBuildAndPackage.bat
    - cd .\..\..\..\
    
build-app:
  stage: build
  artifacts:
    paths:
      - .\SMW-ML\bin\Release\net6.0\
  script:
    - cd .\SMW-ML\
    - dotnet build --configuration Release
    - cd .\..\
    
test-app:
  stage: test
  script:
    - cd .\SMW_ML_TEST\
    - dotnet test
    - cd .\..\
